# Site Settings
title: Ari Vladimir
description: > 
  Mechanical Engineer & Data Analyst. Specialized in transforming complex 
  data into strategic business insights. Expert in Python, SQL, and 
  Advanced Simulation (FEA).
permalink: ':title/'
baseurl: "" # Keep empty for avdeleoncalderon.github.io
url: "https://avdeleoncalderon.github.io"
site-twitter: 

# Author Settings
author: Ari Vladimir de LeÃ³n # Your full name
author-img: avatar.jpg # Upload your photo to assets/img/ and name it avatar.jpg
about-author: >
  Mechanical Engineer and Data Analyst with a solid foundation in Python 
  and SQL. Focused on process optimization, applied statistics, and 
  developing data-driven solutions for executive decision-making.
social-twitter: 
social-facebook: 
social-github: https://github.com/avdeleoncalderon
social-linkedin: https://www.linkedin.com/in/ari-vladimir/
social-email: av.deleoncalderon@gmail.com

# Disqus
discus-identifier: 

# Tracker
analytics: 

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
